name: testapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1

  # for API request
  http: ^0.12.2
  
  # for date
  intl: ^0.16.1
  
  # for keeping data in storage
  shared_preferences: ^0.5.12+4
  
  # for state managing
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - google_fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Black.ttf
          weight: 900
        - asset: google_fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: google_fonts/Roboto-Bold.ttf
          weight: 700
        - asset: google_fonts/Roboto-Light.ttf
          weight: 300
        - asset: google_fonts/Roboto-Medium.ttf
          weight: 500
        - asset: google_fonts/Roboto-Regular.ttf
          weight: 400
        - asset: google_fonts/Roboto-Thin.ttf
          weight: 100